language: php

php:
    - 7.2
    - 7.3
    - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - echo 'extension = "redis.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update

install:
  - composer install --prefer-source $COMPOSER_FLAGS

services:
  - redis

script:
  - ./vendor/bin/phpunit --coverage-text
